% zero_elig.m
function elig = zero_elig(N)
elig = struct('eps_v_noa', zeros(N,1,'single'), ...
    'eps_a', zeros(N,1,'single'), ...
    'Ebar_x', zeros(N,1,'single'), ...
    'Ebar_f', zeros(N,1,'single'));
end

