% Package orientation: Plotting/figure script. It consumes saved result structs or generated arrays and formats diagnostics or publication figures without changing model training.

% make_adLIF_publication_figure
% Publication-quality stacked traces for the BANFF ALIF neuron and eligibility trace.
% Plots (top->bottom): I_in(t), u(t) (+ cosmetic spikes), r(t), w(t), Ebar_f(t).
%
% The original publication styling and stimulus are retained. The traces below
% are generated by BANFF_MODEL, the same simulator used for training/testing:
%   u_hat = E_L + alpha*(u-E_L) + (1-alpha)*(I_tot - w);
%   spike = (u_hat >= V_th); u <- u_hat; u(spike)=V_reset;
% Forward dynamics and eligibility are generated by BANFF_MODEL.
%
% Save outputs next to the script:
%   adLIF_traces.pdf  (vector)
%   adLIF_traces.png  (600 DPI)

%% -------- Parameters (defaults match your training script) ----------
% Time
dt        = 1e-3;                % [s]
T         = 2.0;                 % [s] window to plot
steps     = round(T/dt);

% Figure text and line styling
fs        = 22;                  % axis-label font size
tick_fs   = 20;                  % tick-label font size
lw        = 2.5;                 % trace line width

% Neuron & adaptation
E_L       = -70;                 % [mV]
V_th      = -50;                 % [mV]
V_reset   = -65;                 % [mV]
tau_u     = 50e-3;               % [s]
tau_w     = 500e-3;              % [s]
b_param   = 0.5;                 % [mV], matches current training defaults

% Synaptic filter (same as training head) — dt-invariant, r in Hz
tau_s_rise = 2e-3;               % [s]
tau_s_decay= 50e-3;              % [s]

% Bias (use your init as nominal tonic drive)
B0        = 10.0;                % [mV] tonic bias

% Cosmetic spike visual (biologically plausible peak; see refs)
V_peak_mV = +30.0;               % [mV] overshoot peak for cosmetic spikes
spike_rise_ms = 1.0;             % [ms] visual width
spike_fall_ms = 2.0;             % [ms] visual width

%% -------- Stimulus: reproducible, time-varying input -----------------
rng(7,'twister');
t  = (0:steps-1)*dt;

% Band-limited composite (steps + sin), scaled to elicit clear spiking bursts
I_step = 12.0*(t>0.60 & t<0.90) + 18.0*(t>1.30 & t<1.55);         % [mV]
I_sin  = 8.0*sin(2*pi*5*t) + 4.0*sin(2*pi*11*t);                  % [mV]
I_ext = 16.0 + I_step + I_sin;                                     % [mV], baseline + drive
I_in  = I_ext + B0;                                                % total external drive used in û

%% -------- Single-neuron simulation (uses the publication core) --------
% Keep the original figure layout and stimulus exactly, but obtain the neuron,
% synapse and eligibility traces from BANFF_MODEL so the figure cannot drift
% away from the training/evaluation equations.
core_options = struct( ...
    'N_hidden', 1, 'N_recurrent', 1, 'recurrent_gain', single(0), ...
    'encoder_gain', single(0), 'decoder_gain', single(0.1), ...
    'initial_bias', single(B0), 'dt', single(dt), ...
    'tau_membrane', single(tau_u), 'tau_adaptation', single(tau_w), ...
    'tau_synapse_rise', single(tau_s_rise), ...
    'tau_synapse_decay', single(tau_s_decay), ...
    'resting_voltage', single(E_L), 'threshold_voltage', single(V_th), ...
    'reset_voltage', single(V_reset), 'adaptation_jump', single(b_param), ...
    'eligibility_mode', "hard_spike", 'hard_event_gain', single(1));
core_cfg = banff("config", "breast_cancer", core_options);
P = banff_model('create', 1, 1, core_cfg);

state = struct('u',single(E_L),'w',single(0),'x',single(0),'r',single(0), ...
    'epsilonVoltage',single(0),'epsilonAdaptation',single(0), ...
    'eligibilityRise',single(0),'eligibilityDecay',single(0));
u          = zeros(1,steps,'single') + E_L;
w          = zeros(1,steps,'single');
r          = zeros(1,steps,'single');
S          = false(1,steps);
Ebar_f     = zeros(1,steps,'single');

for k = 1:steps-1
    % I_ext excludes the bias because P.B already contains B0.
    [state, spike] = banff_model('reference_step', P, state, single(I_ext(k)), true);
    u(k+1) = state.u;
    w(k+1) = state.w;
    r(k+1) = state.r;
    S(k+1) = spike;
    Ebar_f(k+1) = state.eligibilityDecay;
end

%% -------- Build cosmetic spike overlays (triangle pulses) -----------
spk_idx = find(S);
tp = []; vp = [];
if ~isempty(spk_idx)
    rise = spike_rise_ms/1e3; fall = spike_fall_ms/1e3;
    for ii = 1:numel(spk_idx)
        ts  = (spk_idx(ii)-1)*dt;
        ttri = [ts - rise, ts, ts + fall];
        vtri = [V_th, V_peak_mV, V_reset];
        tp   = [tp, NaN, ttri]; %#ok<AGROW>
        vp   = [vp, NaN, vtri]; %#ok<AGROW>
    end
end

%% -------- Figure (tiled, tight, print-ready) ------------------------
hFig = figure('Color','w','Units','pixels','Position',[100 100 1000 900]);
tl = tiledlayout(hFig,5,1,'TileSpacing','compact','Padding','compact');

% 1) Input current
nexttile; plot(t, I_in, 'k','LineWidth',lw); xlim([0 T]);
ylabel({'Input', 'Current (a.u.)'},'FontSize',fs); set(gca,'FontSize',tick_fs,'TickDir','out','LineWidth',1); box off;
xticks([]);
ylim([0,60]);
yticks([0,20,40,60]);

% 2) Membrane voltage with cosmetic spikes
nexttile; hold on;
plot(t, u, 'k','LineWidth',lw);                   % LIF trace (piecewise reset)
if ~isempty(tp)
    plot(tp, vp, 'k','LineWidth',0.9);            % cosmetic spikes to +30 mV
end
ymin = min(-75, min(u)-2); ymax = max(V_peak_mV+5, -35);
ylim([ymin ymax]); xlim([0 T]);
ylabel({'Membrane', 'Voltage (mV)'},'FontSize',fs); set(gca,'FontSize',tick_fs,'TickDir','out','LineWidth',1); box off;
xticks([]);
ylim([-70,35]);
yticks([-70,-35,0,35]);

% 3) Synaptically filtered spikes r(t) [Hz, dt-invariant]
nexttile; plot(t, r, 'k','LineWidth',lw);
xlim([0 T]); ylabel({'Filtered', 'Spikes (Hz)'},'FontSize',fs);
set(gca,'FontSize',tick_fs,'TickDir','out','LineWidth',1); box off;
xticks([]);
ylim([0,45]);
yticks([0,15,30,45]);


% 4) Adaptation current w(t)
nexttile; plot(t, w, 'k','LineWidth',lw);
xlim([0 T]); ylabel({'Adaptation', 'Current (a.u.)'},'FontSize',fs);
set(gca,'FontSize',tick_fs,'TickDir','out','LineWidth',1); box off;
xticks([])
yticks([0,2,4,6])
ylim([0,6])

% 5) Synaptically filtered eligibility \bar{E}_f(t)
nexttile; plot(t, Ebar_f, 'k','LineWidth',lw);
xlim([0 T]); ylabel({'Eligibility', 'Trace (a.u.)'},'FontSize',fs); xlabel('Time  (a.u.)','FontSize',fs);
set(gca,'FontSize',tick_fs,'TickDir','out','LineWidth',1); box off;
xticks([0,0.5,1,1.5,2]);
ylim([0,0.12]);
yticks([0,0.04,0.08,0.12])

ax = findall(hFig,'Type','axes');
% Find the minimum x-position among all labels
xpos = arrayfun(@(a) a.YLabel.Position(1), ax);
xmin = min(xpos);

% Set all labels to that x-position
for i = 1:numel(ax)
    ylpos = ax(i).YLabel.Position;
    ax(i).YLabel.Position(1) = xmin-0.05;
    ax(i).YLabel.HorizontalAlignment = 'center'; % keep centred text
end

tl.Padding = 'compact';    % already used
tl.TileSpacing = 'compact';
tl.Padding = 'loose';      % try 'loose' to push plots inwards

% Exports
% (Export commands can be added here if desired)
